kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.app_name }}
spec:
  replicas: {{ .Values.replica_count }}
  selector:
    matchLabels:
      app: {{ .Values.app_name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app_name }}
    spec:
      containers:
        - name: {{ .Values.app_name }}
          image: {{ .Values.image.master }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 50000
              protocol: TCP    
          envFrom:
            - configMapRef:
                name: {{ .Values.app_name }}-env-vars
            - secretRef:
                name: {{ .Values.app_name }}
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
          readinessProbe:
            httpGet:
              path: /login
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 3
            timeoutSeconds: 240
          livenessProbe:
            httpGet:
              path: /login
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 420
            timeoutSeconds: 240
          volumeMounts:
            - name: {{ .Values.app_name }}-data
              mountPath: /var/lib/jenkins
            - name: {{ .Values.app_name }}-trusted-ca-bundle
              mountPath: /etc/pki/ca-trust/source/anchors          
      serviceAccountName: {{ .Values.app_name }}
      volumes:
        - name: {{ .Values.app_name }}-data
          persistentVolumeClaim:
            claimName: {{ .Values.app_name }}
        - name: {{ .Values.app_name }}-trusted-ca-bundle
          configMap:
            name: {{ .Values.app_name }}-trusted-ca-bundle
            optional: true          
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  