kind: ServiceAccount
apiVersion: v1
metadata:
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.jenkins: {{ .Values.service_account_annotation | quote}}
  name: {{ .Values.app_name }}
